export const GOODSDATA = [
  {
    id: 1,
    brand: "Nanoasia",
    group: "makeup",
    name: "NATURAL STAR POWDER WITH PEPTIDES LUXURY TWO TONE",
    price: 5991,
    weight: 15,
    weightType: "гр",
    imgurl: "images/goods/pudra_lux.jpg",
    imgalt: "pudra-lux",
    description:
      "Пудра выполняет три задачи: обеспечивает полноценный дневной уход, выравнивает тон и защищает от солнца. Состоит из двух половинок: теплого и холодного оттенка. Защита SPF 50+",
  },
  {
    id: 2,
    brand: "Nanoasia",
    group: "skinclear",
    name: "Мист EVA JEWELRY MIST",
    price: 3991,
    weight: 100,
    weightType: "мл",
    imgurl: "images/goods/mist.jpg",
    imgalt: "mist",
    description:
      "Питательный кремовый спрей на основе масел, мгновенно питает и увлажняет без ощущения тяжести и пленки на лице.",
  },
  {
    id: 3,
    brand: "Nanoasia",
    group: "skinclear",
    name: "Пилинг гель NANODESSERT AIR BUBBLES PEELING GEL",
    price: 4491,
    weight: 50,
    weightType: "мл",
    imgurl: "images/goods/pilling_bubble.jpg",
    imgalt: "pillling-bubble",
    description:
      "Питательный кремовый спрей на основе масел, мгновенно питает и увлажняет без ощущения тяжести и пленки на лице.",
  },
  {
    id: 4,
    brand: "Nanoasia",
    group: "creams",
    name: "Крем для лица MY CHE FACE CREAM",
    price: 9535,
    weight: 100,
    weightType: "мл",
    imgurl: "images/goods/cream_my_che.jpg",
    imgalt: "cream-che",
    description:
      "Крем с уникальными компонентами, восстанавливает кожу и замедляет старение, после применения крема кожа становиться увлажненной, сияющей, плотной и эластичной.",
  },
  {
    id: 5,
    brand: "Nanoasia",
    group: "creams",
    name: "Крем суфле EVA JEWELRY(40+)",
    price: 12594,
    weight: 50,
    weightType: "мл",
    imgurl: "images/goods/eva-sufle.jpg",
    imgalt: "cream-sufle",
    description:
      "Питательный крем на основе масел и пептидов с мощным лифтинг-эффектов, интенсивно питает, восстанавливает и омолаживает кожу.",
  },
  {
    id: 6,
    brand: "Nanoasia",
    group: "skincare",
    name: "Крем для тела с пептидами NANODESSERT BODY CREAM ",
    price: 4991,
    weight: 100,
    weightType: "мл",
    imgurl: "images/goods/cream-peptide.jpg",
    imgalt: "cream-peptide",
    description:
      "Питательный восстанавливающий крем для лица и тела, убирает шелушение и сухость, мгновенно питает и увлажняет, кожа становиться напитанной, упругой и шелковистой.",
  },
  {
    id: 7,
    brand: "Nanoasia",
    group: "serums",
    name: "Сыворотка для лица NANODESSERT AIR BUBBLES SERUM",
    price: 10800,
    weight: 50,
    weightType: "мл",
    imgurl: "images/goods/nanodesesert-serum.jpg",
    imgalt: "sivorotka-nanodessert",
    description:
      "Невесомая сыворотка направлена на глубокое увлажнения, базовый уход и восстановления кожи. Отлично справляется с сухостью, раздражениями, шелушениями и акне.",
  },
  {
    id: 8,
    brand: "Nanoasia",
    group: "eyecare",
    name: "Крем для кожи вокруг глаз MY CHE EYE CREAM",
    price: 9846,
    weight: 40,
    weightType: "мл",
    imgurl: "images/goods/my_che_eye.jpg",
    imgalt: "my_che_eye",
    description:
      "Питательный крем для век, устраняет симптом «усталость глаз» разглаживает морщины и предотвращает образованию новых.",
  },
  {
    id: 9,
    brand: "Nanoasia",
    group: "makeup",
    name: "Крем кушон JEWELRY RADIANT",
    price: 6262,
    weight: 15,
    weightType: "гр",
    imgurl: "images/goods/couchon-gold.jpg",
    imgalt: "JEWELRY RADIANT",
    description:
      "Кушон выполняет три задачи: выравнивает тон, обеспечивает полноценный уход и защищает от солнца, у кушона покрытие с эффектом естественного сияния. SPF+50.",
  },
  {
    id: 10,
    brand: "Nanoasia",
    group: "makeup",
    name: "Крем кушон NANODESSERT PEPTIDE BC CUSHIOH",
    price: 5120,
    weight: 15,
    weightType: "гр",
    imgurl: "images/goods/couchon-peptide.jpg",
    imgalt: "NANODESSERT PEPTIDE",
    description:
      "Кушон выполняет три задачи: выравнивает тон, обеспечивает полноценный уход и защищает от солнца. Кушон с пептидами имеет ровное матовое покрытие. SPF+50.",
  },
  {
    id: 11,
    brand: "Nanoasia",
    group: "masks",
    name: "Маска для лица SPEEDY FACIAL COOL MESO MASK (100мл)",
    price: 11591,
    weight: 100,
    weightType: "мл",
    imgurl: "images/goods/mezo-mask.jpg",
    imgalt: "SPEEDY FACIAL COOL",
    description:
      "Охлаждающая мезо маска. Восстанавливает кожу после лазеров, пилингов и шлифовок. Дарит долговременный лифтинг-эффект, уменьшает поры, выравнивает тон, мгновенно освежает и оживляет уставшую, тусклую кожу.",
  },
  {
    id: 12,
    brand: "Nanoasia",
    group: "masks",
    name: "Детокс - маска JEJU MARINE (10 пакетов)",
    price: 5991,
    weight: 250,
    weightType: "мл",
    imgurl: "images/goods/jeju-marine-pack.jpg",
    imgalt: "jeju-marine-pack",
    description:
      "Детокс маска на хлопковой основе: наполняет кожу полезными веществами для ее быстрого восстановления и обновления. Мгновенный детокс- эффект восстанавливает кожу и придает естественное сияние. Коробка из 10 пакетов",
  },
  {
    id: 13,
    brand: "Nanoasia",
    group: "skinclear",
    name: "Пенка для умывания NANODESSERT FOAM CLEANSER",
    price: 4291,
    weight: 150,
    weightType: "мл",
    imgurl: "images/goods/dessert-foam-cleanser.jpg",
    imgalt: "NANODESSERT FOAM CLEANSER",
    description:
      "Пенка для умывания с нее начинается красота и здоровье нашей кожи. Это уникальное многофункциональное средство, которое подойдет самой чувствительной коже. Она деликатно очищает и увлажняет, борется с акне, успокаивает кожу, увеличивает кровообращения, регенерацию, упругость.",
  },
  {
    id: 14,
    brand: "Nanoasia",
    group: "skinclear",
    name: "Тоник NANODESSERT PORE CLEAR SOLUTION TONER",
    price: 4391,
    weight: 100,
    weightType: "мл",
    imgurl: "images/goods/toner-pore-clear.jpg",
    imgalt: "NANODESSERT PORE CLEAR SOLUTION TONER",
    description:
      "Тоник способен заменить сразу несколько средств и оказать комплексный эффект и глубокую работу средств из-за уникального сочетания кислот с пептидами.",
  },
  {
    id: 15,
    brand: "Nanoasia",
    group: "eyecare",
    name: "Патчи для глаз PHOENIX UNIVERSE HYDROGEL NANOPATCHES",
    price: 4590,
    weight: 90,
    weightType: "гр",
    imgurl: "images/goods/patch-phoenix.jpg",
    imgalt: "HOENIX UNIVERSE HYDROGEL NANOPATCHES",
    description:
      "Гидрогелевые патчи для быстрого восстановления кожи, мгновенно питают увлажняют и смягчают кожу.",
  },
  {
    id: 16,
    brand: "Nanoasia",
    group: "serums",
    name: "Сыворотка MULTI PEPTIDE SERUM LERA",
    price: 13191,
    weight: 50,
    weightType: "мл",
    imgurl: "images/goods/syvorotka_lera.jpg",
    imgalt: "MULTI PEPTIDE SERUM LERA",
    description:
      "Инновационная мультипептидная сыворотка оказывает мощный омолаживающий и восстанавливающий эффект, замедляет процесс старения, улучшает контур овала лица.",
  },
  {
    id: 17,
    brand: "Nanoasia",
    group: "makeup",
    name: "Блеск для губ REVITAL CLOSS FOR SEDUCTIVE PLUMP LIP",
    price: 5591,
    weight: 6,
    weightType: "мл",
    imgurl: "images/goods/revital-closs-seductive.jpg",
    imgalt: "REVITAL CLOSS FOR SEDUCTIVE PLUMP LIP",
    description:
      "Восстанавливающий блеск для губ-это не просто декоративная косметика, а полноценное уходовое средство, увеличивает обьем, смягчает, увлажняет и питает губы.",
  },
  {
    id: 18,
    brand: "Nanoasia",
    group: "serums",
    name: "Сыворотка Basic Stop TIME MARINE SERUM WITH NANOTIPS",
    price: 5094,
    weight: 30,
    weightType: "мл",
    imgurl: "images/goods/basic-stop-time-marine.jpg",
    imgalt: "TIME MARINE SERUM WITH NANOTIPS",
    description:
      "Cыворотка с наноиглами направлена на глубокое увлажнение и быстрое обновление кожи.",
  },
  {
    id: 19,
    brand: "Nanoasia",
    group: "creams",
    name: "Крем BASIC STOP TIME MARINE COLLAGEN CREAM",
    price: 4491,
    weight: 50,
    weightType: "мл",
    imgurl: "images/goods/basic_stop_time_marine-cream.jpg",
    imgalt: "BASIC STOP TIME MARINE COLLAGEN CREAM",
    description:
      "Крем с растительным коллагеном обеспечивает защиту, восстановление и мгновенный лифтинг эффект с первых минут использования.",
  },
  {
    id: 20,
    brand: "Nanoasia",
    group: "skincare",
    name: "Лосьон для тела BODY LOTION",
    price: 4491,
    weight: 150,
    weightType: "мл",
    imgurl: "images/goods/body-lotion.jpg",
    imgalt: "BODY LOTION",
    description:
      "Лосьон имеет легчайшую текстуру, восстанавливает кожу после солнечных ожогах, уменьшает растяжки на коже, мгновенно питает и увлажняет кожу.",
  },
  {
    id: 21,
    brand: "Nanoasia",
    name: "Мыло для тела HAND AND BODY SOAP",
    price: 2991,
    weight: 150,
    weightType: "мл",
    imgurl: "images/goods/hand-and-body-soap.jpg",
    imgalt: "HAND AND BODY SOAP",
    description:
      "Бережно очищает кожу без стянутости и сухости. Идеально подходит для интимной гигиены.",
  },
  {
    id: 22,
    brand: "Nanoasia",
    name: "ВС тональный крем с пептидами Nanodessert Professional BC Cream With Peptides Golden tanned beige",
    price: 9119,
    weight: 50,
    weightType: "мл",
    imgurl: "images/goods/bc-cream-golden-tanned.jpg",
    imgalt: "HAND AND BODY SOAP",
    description:
      "Оттенок: Golden tanned beige. Бережно очищает кожу без стянутости и сухости. Идеально подходит для интимной гигиены.",
  },
  {
    id: 23,
    brand: "Nanoasia",
    name: "ВС тональный крем с пептидами Nanodessert Professional BC Cream With Peptides Natural Begie",
    price: 9119,
    weight: 50,
    weightType: "мл",
    imgurl: "images/goods/bc-cream-natural.jpg",
    imgalt: "HAND AND BODY SOAP",
    description:
      "Оттенок: Natural Begie. Бережно очищает кожу без стянутости и сухости. Идеально подходит для интимной гигиены.",
  },
  {
    id: 24,
    brand: "Nanoasia",
    group: "masks",
    name: "Детокс - маска JEJU MARINE (5 пакетов)",
    price: 3295,
    weight: 125,
    weightType: "мл",
    imgurl: "images/goods/jeju-marine-one-pick.jpg",
    imgalt: "jeju-marine-pack",
    description:
      "5 пакетов детокс масок на хлопковой основе: наполняет кожу полезными веществами для ее быстрого восстановления и обновления. Мгновенный детокс- эффект восстанавливает кожу и придает естественное сияние. Коробка из 10 пакетов",
  },
  {
    id: 25,
    brand: "Nanoasia",
    group: "masks",
    name: "Детокс - маска JEJU MARINE (1 пакет)",
    price: 719,
    weight: 25,
    weightType: "мл",
    imgurl: "images/goods/jeju-marine-one-pick.jpg",
    imgalt: "jeju-marine-pack",
    description:
      "1 пакет детокс маски на хлопковой основе: наполняет кожу полезными веществами для ее быстрого восстановления и обновления. Мгновенный детокс- эффект восстанавливает кожу и придает естественное сияние. Коробка из 10 пакетов",
  },
  {
    id: 26,
    brand: "Nanoasia",
    group: "makeup",
    name: "NATURAL STAR POWDER WITH PEPTIDES STANDART TWO TONE",
    price: 4901,
    weight: 15,
    weightType: "гр",
    imgurl: "images/goods/pudra-standart.jpg",
    imgalt: "pudra-standart",
    description:
      "Пудра выполняет три задачи: обеспечивает полноценный дневной уход, выравнивает тон и защищает от солнца. Состоит из двух половинок: теплого и холодного оттенка. Защита SPF 50+",
  },
];
